### ISSUE TITLE
Pneumatic line

### ISSUE THREAD

**Issue by eplotner** [circuitdiagram/components#10]
May not be completely in the scope of this but a few pneumatic components would be nice.

**Comment by Corsaka** [comment]
These?
![image](https://user-images.githubusercontent.com/23699128/55291485-ddc08800-53d6-11e9-9704-beb86b728106.png)

**Comment by eplotner** [comment]
Yes.

**Comment by SamuelFisher** [comment]
I think this is a tricky one because it seems like pneumatic components are distinct to electronic components, and they really belong to a different type of diagram which is so far not what Circuit Diagram has aimed to provide.

I also don't think it makes sense to be able to use both types of components in the same diagram.
